#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2016 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

set -e
replaceparam=$1

 echo ""
 echo "***********************************************"
if [ "$replaceparam" != "replace" ] ; then
 echo "Performing jsbeautify check on all js resources"
else
 echo "Performing jsbeautify replacement on all js resources"
fi
 echo "***********************************************"
 echo ""
files=$(../org.openbravo.client.kernel/jscheck/jsfiles ./)

for changedfile in echo $files;
do
  if [ -f "$changedfile" -a -n "$(echo $changedfile | awk '/.js$/')" ]; then
  source ../org.openbravo.client.kernel/jsbeautify/jsbeautify-module $changedfile $replaceparam
  fi
done
exit $ERROR