
package ec.cusoft.facturaec.pruebas.autorizacion;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-417-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AutorizacionComprobantesService", targetNamespace = "http://ec.gob.sri.ws.autorizacion", wsdlLocation = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl")
public class AutorizacionComprobantesService
    extends Service
{

    private final static URL AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ec.cusoft.facturaec.pruebas.autorizacion.AutorizacionComprobantesService.class.getName());
    private final static WebServiceException AUTORIZACIONCOMPROBANTESSERVICE_EXCEPTION;
    private final static QName AUTORIZACIONCOMPROBANTESSERVICE_QNAME = new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesService");


    static {
        URL url = null;
        WebServiceException e = null;
        try {
            URL baseUrl;
            baseUrl = ec.cusoft.facturaec.pruebas.autorizacion.AutorizacionComprobantesService.class.getResource(".");
            url = new URL(baseUrl, "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl");
        } catch (MalformedURLException ex) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl', retrying as a local file");
            logger.warning(ex.getMessage());
        }
        AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION = url;
        AUTORIZACIONCOMPROBANTESSERVICE_EXCEPTION = e;
    }

/*    public AutorizacionComprobantesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutorizacionComprobantesService() {
        super(AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION, new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesService"));
    }

    /**
     * 
     * @return
     *     returns AutorizacionComprobantes
     *//*
    @WebEndpoint(name = "AutorizacionComprobantesPort")
    public AutorizacionComprobantes getAutorizacionComprobantesPort() {
        return super.getPort(new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesPort"), AutorizacionComprobantes.class);
    }

    *//**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizacionComprobantes
     *//*
    @WebEndpoint(name = "AutorizacionComprobantesPort")
    public AutorizacionComprobantes getAutorizacionComprobantesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesPort"), AutorizacionComprobantes.class, features);
    }

}
*/
    

    public AutorizacionComprobantesService() {
        super(__getWsdlLocation(), AUTORIZACIONCOMPROBANTESSERVICE_QNAME);
    }

    
    /*public AutorizacionComprobantesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTORIZACIONCOMPROBANTESSERVICE_QNAME, features);    	
    }*/

    public AutorizacionComprobantesService(URL wsdlLocation) {
        super(wsdlLocation, AUTORIZACIONCOMPROBANTESSERVICE_QNAME);
    }

    
    /*public AutorizacionComprobantesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTORIZACIONCOMPROBANTESSERVICE_QNAME, features);
    }*/

    public AutorizacionComprobantesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    
    /*public AutorizacionComprobantesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns AutorizacionComprobantes
     */
    @WebEndpoint(name = "AutorizacionComprobantesPort")
    public AutorizacionComprobantes getAutorizacionComprobantesPort() {
        return super.getPort(new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesPort"), AutorizacionComprobantes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizacionComprobantes
     */
    @WebEndpoint(name = "AutorizacionComprobantesPort")
    public AutorizacionComprobantes getAutorizacionComprobantesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesPort"), AutorizacionComprobantes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTORIZACIONCOMPROBANTESSERVICE_EXCEPTION!= null) {
            throw AUTORIZACIONCOMPROBANTESSERVICE_EXCEPTION;
        }
        return AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION;
    }

}
