#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2016 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

set -e
# Mercurial pre-commit hook for jsbeautify

changedfile=$1
replaceparam=$2
./modules/org.openbravo.client.kernel/jsbeautify/jsbeautifier.py --indent-size=2 --jslint-happy "$changedfile" | perl -pe 'chop if eof' > "$changedfile.beautified"
if ! diff -u "$changedfile" "$changedfile.beautified"; then
  if [ "$replaceparam" != "replace" ] ; then
    echo ""
    echo "******************************************************************************************************************************************************"
    echo "See above Beautify Error --> Please, beautify $changedfile";
    echo "******************************************************************************************************************************************************"
    echo "*Note: JS Beautifier Eclipse plugin doesn't remove white spaces at the end of the line in block comments. You have to do it manually"
    echo ""
    rm -rf "$changedfile.beautified"
    export ERROR="1"
  else
    cat "$changedfile.beautified" > "$changedfile"
    echo "Beautify --> File beautified: $changedfile";
  fi
fi
rm -rf "$changedfile.beautified"